twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        avatarsPath: "%avatarsPath%"
        figuresPath: "%figuresPath%"
        avatarDefault: "%avatarDefault%"
        figureDefault: "%figureDefault%"
when@test:
    twig:
        strict_variables: true
